//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEdit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbEdit.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DbEdit config file was not found in the current directory.
        ///Select a directory to map to a database table..
        /// </summary>
        internal static string GetFolderDesc {
            get {
                return ResourceManager.GetString("GetFolderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all existing files?.
        /// </summary>
        internal static string MsgConfirmDelete {
            get {
                return ResourceManager.GetString("MsgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got exception trying to load from database:.
        /// </summary>
        internal static string MsgDbLoadException {
            get {
                return ResourceManager.GetString("MsgDbLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate file name {0}. .
        /// </summary>
        internal static string MsgDuplicate {
            get {
                return ResourceManager.GetString("MsgDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping subsequent ones.  
        ///Check query to make sure keys are unique..
        /// </summary>
        internal static string MsgDuplicateDetails {
            get {
                return ResourceManager.GetString("MsgDuplicateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve config.
        /// </summary>
        internal static string MsgFailedToGetConfig {
            get {
                return ResourceManager.GetString("MsgFailedToGetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First parameter must be config file.
        /// </summary>
        internal static string MsgFirstNotFile {
            get {
                return ResourceManager.GetString("MsgFirstNotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings are filled in with sample data.  Enter data specific to your object..
        /// </summary>
        internal static string MsgFirstTime {
            get {
                return ResourceManager.GetString("MsgFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use bulk load option, first parameter must be a {0} file.
        /// </summary>
        internal static string MsgFormatBulk {
            get {
                return ResourceManager.GetString("MsgFormatBulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating destination folder &quot;{0}&quot;:
        ///{1}.
        /// </summary>
        internal static string MsgFormatDestCreatError {
            get {
                return ResourceManager.GetString("MsgFormatDestCreatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbEdit is a tool for getting and updating text columns from a database
        ///  Usage: DbEdit {0} |-l[x]|-s &lt;source&gt; &lt;dest&gt; &lt;orig&gt; or -b &lt;config&gt; [&lt;content dest&gt;]
        ///
        ///      {0}  used along loads the files into the folder of the config file with the files specified in the config file.\r\n&quot; +
        ///      -l loads one file from source into dest with orig being source.
        ///      -lx loads and formats XML files
        ///      -s SaveFile one file from source into dest with orig being the original file.
        ///
        ///   See help doc for more deta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgFormatHelp {
            get {
                return ResourceManager.GetString("MsgFormatHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select statement in &quot;{0}&quot; is invalid..
        /// </summary>
        internal static string MsgFormatInvalidSelect {
            get {
                return ResourceManager.GetString("MsgFormatInvalidSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} file{1} from database.
        /// </summary>
        internal static string MsgFormatLoaded {
            get {
                return ResourceManager.GetString("MsgFormatLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; does not exist.
        /// </summary>
        internal static string MsgFormatNotExist {
            get {
                return ResourceManager.GetString("MsgFormatNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update updated {0} rows.  Update aborted..
        /// </summary>
        internal static string MsgFormatUpdated {
            get {
                return ResourceManager.GetString("MsgFormatUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got exception trying to load tenant:.
        /// </summary>
        internal static string MsgLoadException {
            get {
                return ResourceManager.GetString("MsgLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename must have at least Name before stop char.
        /// </summary>
        internal static string MsgMissingName {
            get {
                return ResourceManager.GetString("MsgMissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Update statement found.  Saving not allowed.
        /// </summary>
        internal static string MsgNoUpdate {
            get {
                return ResourceManager.GetString("MsgNoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select statemtent must include keys after content.
        /// </summary>
        internal static string MsgSelectMissingKey {
            get {
                return ResourceManager.GetString("MsgSelectMissingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build SQL command.
        /// </summary>
        internal static string MsgSqlFailed {
            get {
                return ResourceManager.GetString("MsgSqlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbEdit.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
